name: Update Lifetime Commit Count

on:
  schedule: [{ cron: "0 3 * * 1" }]   # weekly
  workflow_dispatch:                  # manual trigger

jobs:
  tally:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      USERNAME: Seelammahesh
      AUTHOR_REGEX: "(Seelam[ ]*Mahesh|maheshmasina@gmail.com|Seelammahesh@users.noreply.github.com)"

    steps:
      - name: Checkout profile repo
        uses: actions/checkout@v4

      - name: Install gh & jq
        run: |
          sudo apt-get update -y
          sudo apt-get install -y jq gh

      - name: List repos (skip forks)
        run: |
          gh repo list "$USERNAME" --limit 300 --json name,isFork \
            | jq '[.[] | select(.isFork == false)]' > repos.json
          echo "Repo count: $(jq 'length' repos.json)"

      - name: Count commits across all repos & branches
        id: count
        run: |
          set -e
          total=0
          mkdir work && cd work

          for name in $(jq -r '.[].name' ../repos.json); do
            echo "::group::Repo ${name}"
            git clone --filter=blob:none --no-checkout "https://github.com/${USERNAME}/${name}.git" "$name" || { echo "skip $name"; echo "::endgroup::"; continue; }
            cd "$name"
            git fetch --all --quiet --tags
            c=$(git log --all --author="${AUTHOR_REGEX}" --pretty=oneline | wc -l || true)
            echo "Commits by you: $c"
            total=$((total + c))
            cd ..
            echo "::endgroup::"
          done

          echo "TOTAL=${total}"
          echo "total=$total" >> $GITHUB_OUTPUT

      - name: Update README marker
        run: |
          COUNT="${{ steps.count.outputs.total }}"
          FILE="README.md"
          START="<!--LIFETIME_COMMITS-->"
          END="<!--/LIFETIME_COMMITS-->"
          LINE="${START} Lifetime commits across all repositories: ${COUNT} ${END}"

          if grep -q "$START" "$FILE"; then
            awk -v s="$START" -v e="$END" -v r="$LINE" '
              BEGIN{inblk=0}
              {
                if(index($0,s)){print r; inblk=1; next}
                if(index($0,e)){inblk=0; next}
                if(!inblk) print
              }
            ' "$FILE" > README.tmp && mv README.tmp "$FILE"
          else
            printf "\n%s\n" "$LINE" >> "$FILE"
          fi

          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add "$FILE"
          git commit -m "chore: update lifetime commit total to ${COUNT}" || echo "No README changes"
          git push
